services:
  app:
    image: instafeed
    ports:
      - 8443
    environment:
      - CONECTION_STRING=mongodb://mongo:27017
      - REDIS_HOST=redis
  mongo:
    image: mongo
    ports:
      - 27019:27017
  redis:
    image: redis
    ports:
      - 6379
  nginx:
    image: nginx
    ports:
      - 8443:443
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./cert/server.cert:/etc/nginx/server.cert
      - ./cert/server.key:/etc/nginx/server.key
