services:
  app:
    image: instafeed
    ports:
      - 8443
    environment:
      - CONECTION_STRING=mongodb://mongo:27017
  mongo:
    image: mongo
    ports:
      - 27019:27017
  nginx:
    image: nginx
    ports:
      - 8443:443
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./cert/server.cert:/etc/nginx/server.cert
      - ./cert/server.key:/etc/nginx/server.key
